/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XsqeYAjDOrA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function Maindashboard() {
  return (
    <div className="min-h-screen p-4 bg-gray-100">
      <header className="flex justify-between items-center mb-4">
        <h1 className="text-2xl font-bold"></h1>
        <SettingsIcon className="w-6 h-6" />
      </header>
      <div className="flex items-center mb-4">
        <label htmlFor="search" className="mr-2">
          Find
        </label>
        <Input id="search" placeholder="Search..." className="mr-4" />
        <label htmlFor="rows" className="mr-2">
          Rows per page:
        </label>
        <Input id="rows" type="number" defaultValue="100" className="w-20" />
        <Button className="ml-4">New Review</Button>
      </div>
      <div className="overflow-x-auto">
        <Table className="min-w-full bg-white border border-gray-200">
          <TableHeader>
            <TableRow className="bg-blue-200">
              <TableHead className="text-center">
                COLUMN 1 <ListOrderedIcon className="inline w-4 h-4" />
              </TableHead>
              <TableHead className="text-center">
                COLUMN 2 <ListOrderedIcon className="inline w-4 h-4" />
              </TableHead>
              <TableHead className="text-center">
                COLUMN 3 <ListOrderedIcon className="inline w-4 h-4" />
              </TableHead>
              <TableHead className="text-center">
                COLUMN 4 <ListOrderedIcon className="inline w-4 h-4" />
              </TableHead>
              <TableHead className="text-center">ACTIONS</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {Array.from({ length: 5 }).map((_, index) => (
              <TableRow key={index}>
                <TableCell className="text-center">Data 1</TableCell>
                <TableCell className="text-center">Data 2</TableCell>
                <TableCell className="text-center">Data 3</TableCell>
                <TableCell className="text-center">Data 4</TableCell>
                <TableCell className="text-center">
                  <Button variant="outline">Edit</Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <div className="flex justify-between items-center mt-4">
        <Button variant="outline">Previous</Button>
        <span>
    
        </span>
        <Button variant="outline">Next</Button>
      </div>
    </div>
  )
}

function ListOrderedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" x2="21" y1="6" y2="6" />
      <line x1="10" x2="21" y1="12" y2="12" />
      <line x1="10" x2="21" y1="18" y2="18" />
      <path d="M4 6h1v4" />
      <path d="M4 10h2" />
      <path d="M6 18H4c0-1 2-2 2-3s-1-1.5-2-1" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
